export const GET_EXPERIENCE_REQUEST = "GET_EXPERIENCE_REQUEST";
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS";
export const GET_EXPERIENCE_FAIL = "GET_EXPERIENCE_FAIL";

export const POST_EXPERIENCE_REQUEST = "POST_EXPERIENCE_REQUEST";
export const POST_EXPERIENCE_SUCCESS = "POST_EXPERIENCE_SUCCESS";
export const POST_EXPERIENCE_FAIL = "POST_EXPERIENCE_FAIL";