export const GET_GALLERY_REQUEST = "GET_GALLERY_REQUEST";
export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS";
export const GET_GALLERY_FAIL = "GET_GALLERY_FAIL";

export const POST_GALLERY_REQUEST = "POST_GALLERY_REQUEST";
export const POST_GALLERY_SUCCESS = "POST_GALLERY_SUCCESS";
export const POST_GALLERY_FAIL = "POST_GALLERY_FAIL";