export const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
export const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
export const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";

export const POST_PROJECTS_REQUEST = "POST_PROJECTS_REQUEST";
export const POST_PROJECTS_SUCCESS = "POST_PROJECTS_SUCCESS";
export const POST_PROJECTS_FAIL = "POST_PROJECTS_FAIL";