export const GET_SKILLS_REQUEST = "GET_SKILLS_REQUEST";
export const GET_SKILLS_SUCCESS = "GET_SKILLS_SUCCESS";
export const GET_SKILLS_FAIL = "GET_SKILLS_FAIL";

export const POST_SKILLS_REQUEST = "POST_SKILLS_REQUEST";
export const POST_SKILLS_SUCCESS = "POST_SKILLS_SUCCESS";
export const POST_SKILLS_FAIL = "POST_SKILLS_FAIL";